project_id = "nhbuivrsbiivimeoyqqr"

[functions.create-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.get-download]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.drive-init-upload]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.resend-download]
verify_jwt = true

[functions.manage-admins]
verify_jwt = true

[functions.drive-usage]
verify_jwt = true